apiVersion: v1
kind: Secret
metadata:
  name: ai-secret
  namespace: wicstock-ai
  labels:
    app: ai-service
    app.kubernetes.io/part-of: wicstock
type: Opaque
stringData:
  DB_PASSWORD: "wicstock_dev_password_2026!"
