apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: wicstock-core
  labels:
    app: postgres
    app.kubernetes.io/part-of: wicstock
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Volume de dev léger pour limiter l'impact disque
