apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: wicstock-core
  labels:
    app: backend
    app.kubernetes.io/part-of: wicstock
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Jwt__Issuer: "WicStock"
  WicStockIAUrl: "http://ai-service.wicstock-ai.svc.cluster.local:8000/"
