apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  namespace: wicstock-observability
  labels:
    app: prometheus
    app.kubernetes.io/part-of: wicstock
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "wicstock-backend"
        metrics_path: "/metrics"
        static_configs:
          - targets: ["backend-service.wicstock-core.svc.cluster.local:8080"]
            labels:
              application: "wicstock-api"
              environment: "k8s-dev"
