apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
  namespace: wicstock-core
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    Jwt__Secret: AgBy2uXh6kL...
    ConnectionStrings__DefaultConnection: AgBy2uXh6kL...
  template:
    metadata:
      name: backend-secret
      namespace: wicstock-core
    type: Opaque
