apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: wicstock-observability
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    admin-user: AgBy2uXh6kL...
    admin-password: AgBy2uXh6kL...
  template:
    metadata:
      name: grafana-secret
      namespace: wicstock-observability
    type: Opaque
