apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: wicstock-core
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    POSTGRES_USER: AgBy2uXh6kL...
    POSTGRES_PASSWORD: AgBy2uXh6kL...
    POSTGRES_DB: AgBy2uXh6kL...
  template:
    metadata:
      name: postgres-secret
      namespace: wicstock-core
    type: Opaque
