{{- if and .Values.ingress.enabled .Values.modules.core.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wicstock.fullname" . }}-ingress
  labels:
    {{- include "wicstock.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "wicstock.fullname" . }}-frontend-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "wicstock.fullname" . }}-backend-service
                port:
                  number: 8080
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: {{ include "wicstock.fullname" . }}-backend-service
                port:
                  number: 8080
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: {{ include "wicstock.fullname" . }}-backend-service
                port:
                  number: 8080
{{- end }}
