apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wicstock-core
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/HaifaCheikh/WicStockProject.git
      targetRevision: feat/k8s-namespaces-validation
      ref: values
    - repoURL: https://github.com/HaifaCheikh/WicStockProject.git
      targetRevision: feat/k8s-namespaces-validation
      path: helm/wicstock
      helm:
        valueFiles:
          - $values/gitops/environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wicstock-core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
